[build]
  base = "klmk/Project"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.0.0"
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
